### ISSUE TITLE
AddOn yform_adminer konnte aus folgendem Grund nicht aktualisiert werden: Es wird das AddOn dminer ^1 benötigt! 

### ISSUE THREAD

**Issue by my-steffen** [FriendsOfREDAXO/yform_adminer#23]
Beim update von 1.4.0 auf 1.4.1. Glaub iwas passt in der package.yml nicht. Habe nämlich adminer 2.0.2 drauf. :)

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/yform_adminer/blob/f257f55beda230c6684e4e69eb13b859fa5d9278/package.yml#L11 

Hier steht dminer anstelle von adminer und das Adminer-AddOn hat mittlerweile Version 2.x erreicht, wegen der Umstellung auf Adminerevo

**Comment by my-steffen** [comment]
Dankeschön :)
